#!/bin/csh

set codeDir = /glade/u/home/chen/idealized/postprocessing/plevel

set options = "-fno-alias -fltconsistency -ftz -g -O2 -i4 -r8 -nowarn -Wp,-w -fpe0"

ifort $options -I/usr/local/include -I/glade/u/home/chen/idealized/netcdf/include $codeDir/plev_constants.F90 $codeDir/moisture_convert.F90 \
         $codeDir/pressure_interp.F90 $codeDir/pinterp_utilities.F90 $codeDir/run_pressure_interp.F90 \
                       -o PLEV.exe -L/glade/u/home/chen/idealized/netcdf/lib -lnetcdf

rm -f *.mod
set options = "-fno-alias -fltconsistency -ftz -g -O2 -i4 -nowarn -Wp,-w -fpe0"

ifort $options -I/usr/local/include -I/glade/u/home/chen/idealized/netcdf/include $codeDir/plev_constants.F90 $codeDir/moisture_convert.F90 \
         $codeDir/pressure_interp.F90 $codeDir/pinterp_utilities.F90 $codeDir/run_pressure_interp.F90 \
                        -o PLEV.r4.exe -L/glade/u/home/chen/idealized/netcdf/lib -lnetcdf
